services:
  - type: web
    name: ace
    env: docker
    dockerfilePath: ./DockerACE/Dockerfile
    envVars:
      - key: PORT
        value: 6878
    disk:
      name: ace_data
      mountPath: /srv/ace
      sizeGB: 2 # Укажите необходимый размер диска
    plan: starter

  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./DockerNGINX/Dockerfile
    envVars:
      - key: PORT
        value: 80
    plan: starter